# Generated by Django 4.0.4 on 2022-06-01 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_Categorie', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nom_Categorie', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id_Commentaire', models.BigAutoField(primary_key=True, serialize=False)),
                ('Commentaire', models.TextField(max_length=2500)),
                ('Email', models.EmailField(max_length=50)),
                ('Nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id_Element', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nom_Element', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Elements', to='fun_kids.categorie')),
            ],
        ),
    ]
